var action_type_modifiers = IntArray([1, 3, 1, 1, 2, 2])
var capture_modifiers = IntArray([5, 2, 1])
var attack_modifiers = IntArray([3, 6, 8])
var move_capture_modifiers = IntArray([5, 2, 2])
var move_attack_modifiers = IntArray([2, 2, 3])